name: example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_hook_form_generator:
    path: ../flutter_hook_form_generator/
  flutter_hook_form_annotation:
    path: ../flutter_hook_form_annotation/
  flutter_zod:
    path: ../flutter_zod/
  flutter_hook_form:
    path: ../flutter_hook_form/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:

flutter:
  uses-material-design: true
