builders:
  generators:
    # target: ":generators"
    import: "package:flutter_hook_form_generator/flutter_hook_form_generator.dart"
    builder_factories: ["generateJsonClass"]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
    
    # build_to: source